### ISSUE TITLE
-(void)scrollToPage:(int)page animated:(BOOL)animated

### ISSUE THREAD

**Issue by magnett** [TomThorpe/UIScrollSlidingPages#14]
Thanks of all i would like to thank you for this excellent control.
I am having issues implementing the scrollToPage function.
I have a master view with two uitableview controllers. I want when the user selects a row in the tableview, to change the page to the next page (i have only two pages). I have tried all possible ways i could imaging and failed. Below are some examples i tried in my first UITableView controller:

[[ContainerVC alloc].slider scrollToPage:1 animated:YES];

ContainerVC *controller = [self.storyboard instantiateViewControllerWithIdentifier:@"containerVC"];
[controller.slider scrollToPage:1 animated:TRUE]; 

[[ContainerVC alloc] scrollToPage:1 animated:YES];

[[TTScrollSlidingPagesController alloc] scrollToPage:1 animated:YES];

Could you please provide an example using this function?

**Comment by Unaigo** [comment]
Hi Tom, I try to implement scrolltoPage , with SWRevealViewController, but in the TTViewControler if I make a void, and I write [self.slider scrollToPage:1 animated:YES], don't make anything, I don't undersand why, because the void is working good ( I write in console "Enter the void", and is working ok), but the line of scrollTopage is invisible for my app :( . Thank's
