### ISSUE TITLE
NavigationBar

### ISSUE THREAD

**Issue by varatep** [TomThorpe/UIScrollSlidingPages#39]
Is it possible to get this to work with UINavigationBar of a UINavigationController?

**Comment by varatep** [comment]
Got it to work with instantiating another UINavigationController. Looks a bit funky, though. Is there a recommended way of being able to dismiss the "TTScrollSlidingPagesController" ?

**Comment by TomThorpe** [comment]
Not really, sorry. My intention is that this would always be the top level controller, because I think having it along with a navigation controller could confuse things from a UX point of view (especially with conflicting gestures like the back gesture in a navigation controller which could conflict with the scroll on this controller).

So it's not a high priority for me now, sorry :( I'll be sure to update this if I change it in the future though.
